import type { Service } from '@/types';

export const STATIC_SERVICES: Service[] = [
  {
    id: "01",
    slug: "custom-e-commerce-development",
    service_category_id: 1,
    category: {"id":1,"name":"E Commerce Website","slug":"e-commerce-website","icon":"cart","is_active":true,"sort_order":1},
    icon: "cart",
    color: "#ec4899",
    title: "Custom E-commerce Development",
    description:
      "Fully custom online store built for performance, conversions, and scalability.",
    features: [
      "Custom UI/UX design (mobile-first)",
      "WooCommerce / Headless Commerce / Shopify integration",
      "Secure payment gateway (Stripe, SSLCommerz, PayPal)",
      "Order, inventory & customer management system",
      "Coupon, discount & promotion system",
      "Multi-currency & multi-language support",
    ],
  },
  {
    id: "02",
    slug: "business-website-development",
    service_category_id: 1,
    category: {"id":1,"name":"E Commerce Website","slug":"e-commerce-website","icon":"cart","is_active":true,"sort_order":1},
    icon: "globe",
    color: "#2563eb",
    title: "Business Website Development",
    description:
      "Modern, fast and SEO optimized websites for companies and startups.",
    features: [
      "Next.js / React / Laravel development",
      "SEO optimized structure (Core Web Vitals)",
      "CMS integration (WordPress / Headless CMS)",
      "Lightning fast performance",
      "Blog & content management system",
    ],
  },
  {
    id: "03",
    slug: "mobile-app-development",
    service_category_id: 1,
    category: {"id":1,"name":"E Commerce Website","slug":"e-commerce-website","icon":"cart","is_active":true,"sort_order":1},
    icon: "mobile",
    color: "#10b981",
    title: "Mobile App Development",
    description:
      "Cross-platform mobile apps for Android & iOS with smooth UX.",
    features: [
      "React Native / Flutter apps",
      "Push notifications system",
      "API integration with backend",
      "Offline support features",
      "Play Store & App Store deployment",
    ],
  },
  {
    id: "04",
    slug: "multi-vendor-marketplace-system",
    service_category_id: 2,
    category: {"id":2,"name":"Multi Vendor E Commerce","slug":"multi-vendor-e-commerce","icon":"store","is_active":true,"sort_order":2},
    icon: "store",
    color: "#12d7df",
    title: "Multi Vendor Marketplace System",
    description:
      "Build your own Amazon-style marketplace with vendor management system.",
    features: [
      "Vendor registration & dashboard",
      "Commission management system",
      "Product approval workflow",
      "Separate seller & admin panel",
      "Order splitting & tracking system",
      "Payout & earnings management",
    ],
  },
  {
    id: "05",
    slug: "pos-inventory-system",
    service_category_id: 2,
    category: {"id":2,"name":"Multi Vendor E Commerce","slug":"multi-vendor-e-commerce","icon":"store","is_active":true,"sort_order":2},
    icon: "invoice",
    color: "#7c3aed",
    title: "POS & Inventory System",
    description:
      "Smart POS system for retail business with real-time stock control.",
    features: [
      "Barcode & QR code scanning",
      "Real-time stock management",
      "Multiple branch support",
      "Sales reporting dashboard",
      "Invoice & billing system",
    ],
  },
  {
    id: "06",
    slug: "custom-software-development",
    service_category_id: 2,
    category: {"id":2,"name":"Multi Vendor E Commerce","slug":"multi-vendor-e-commerce","icon":"store","is_active":true,"sort_order":2},
    icon: "code",
    color: "#0037d8",
    title: "Custom Software Development",
    description: "Enterprise-level software tailored for your business needs.",
    features: [
      "Custom CRM / ERP systems",
      "REST & GraphQL API development",
      "Microservice architecture",
      "Database design & optimization",
      "Cloud deployment (AWS / VPS)",
    ],
  },
  {
    id: "07",
    slug: "ui-ux-design-system",
    service_category_id: 5,
    category: {"id":5,"name":"Landing Page","slug":"landing-page","icon":"layout","is_active":true,"sort_order":5},
    icon: "palette",
    color: "#0ea5e9",
    title: "UI/UX Design System",
    description:
      "Modern design system that improves user experience and conversion rate.",
    features: [
      "Figma design system",
      "User journey mapping",
      "Wireframing & prototyping",
      "Mobile-first UI design",
      "Conversion-focused design",
    ],
  },
  {
    id: "08",
    slug: "learning-management-system",
    service_category_id: 3,
    category: {"id":3,"name":"Learning Management System","slug":"learning-management-system","icon":"book","is_active":true,"sort_order":3},
    icon: "book",
    color: "#eab308",
    title: "Learning Management System (LMS)",
    description:
      "Complete online learning platform for schools, academies and coaching centers.",
    features: [
      "Course creation & management",
      "Student enrollment system",
      "Video learning module",
      "Quiz & exam system",
      "Certificate generation",
    ],
  },
  {
    id: "09",
    slug: "digital-marketing-service",
    service_category_id: 3,
    category: {"id":3,"name":"Learning Management System","slug":"learning-management-system","icon":"book","is_active":true,"sort_order":3},
    icon: "megaphone",
    color: "#a855f7",
    title: "Digital Marketing Service",
    description: "Grow your business with data-driven marketing strategies.",
    features: [
      "SEO optimization",
      "Facebook & Google Ads setup",
      "Social media marketing",
      "Email marketing funnels",
      "Analytics & conversion tracking",
    ],
  },
  {
    id: "12",
    slug: "pharmacy-management-system",
    service_category_id: 4,
    category: {"id":4,"name":"Pharmacy Website & POS","slug":"pharmacy-website-pos","icon":"shield","is_active":true,"sort_order":4},
    icon: "truck",
    color: "#ef4444",
    title: "Pharmacy Management System",
    description:
      "Complete digital pharmacy solution with POS, inventory, prescription and customer management system.",
    features: [
      "Medicine inventory management (batch & expiry tracking)",
      "Barcode-based POS billing system",
      "Doctor prescription upload & verification",
      "Low stock & expiry alert system",
      "Supplier & purchase management",
      "Sales & profit reporting dashboard",
    ],
  },
  {
    id: "13",
    slug: "pharmacy-e-commerce-store",
    service_category_id: 4,
    category: {"id":4,"name":"Pharmacy Website & POS","slug":"pharmacy-website-pos","icon":"shield","is_active":true,"sort_order":4},
    icon: "invoice",
    color: "#f97316",
    title: "Pharmacy E-commerce Store",
    description:
      "Online medicine ordering platform with doorstep delivery and prescription upload system.",
    features: [
      "Online medicine ordering system",
      "Prescription upload (image/PDF)",
      "Cart & checkout system",
      "Delivery tracking integration",
      "Customer account & order history",
      "Location-based delivery system",
    ],
  },
  {
    id: "14",
    slug: "pharmacy-pos-billing-software",
    service_category_id: 4,
    category: {"id":4,"name":"Pharmacy Website & POS","slug":"pharmacy-website-pos","icon":"shield","is_active":true,"sort_order":4},
    icon: "server",
    color: "#22c55e",
    title: "Pharmacy POS Billing Software",
    description:
      "Fast and reliable POS system for retail pharmacies with full billing automation.",
    features: [
      "Quick billing with barcode scanner",
      "Medicine search & auto-suggestion",
      "Daily sales & cash management",
      "Multiple cashier support",
      "Discount & coupon system",
      "Print invoice & receipt system",
    ],
  },
  {
    id: "10",
    slug: "high-conversion-landing-page",
    service_category_id: 5,
    category: {"id":5,"name":"Landing Page","slug":"landing-page","icon":"layout","is_active":true,"sort_order":5},
    icon: "layout",
    color: "#06b6d4",
    title: "High Conversion Landing Page",
    description:
      "Landing pages designed to convert visitors into leads or sales.",
    features: [
      "Fast loading pages",
      "Mobile responsive design",
      "Lead capture forms",
      "A/B testing ready",
      "SEO optimized structure",
    ],
  },
  {
    id: "11",
    slug: "product-startup-showcase",
    service_category_id: 5,
    category: {"id":5,"name":"Landing Page","slug":"landing-page","icon":"layout","is_active":true,"sort_order":5},
    icon: "rocket",
    color: "#8b5cf6",
    title: "Product & Startup Showcase",
    description:
      "Modern showcase website for startups, SaaS products and apps.",
    features: [
      "Modern UI animations",
      "Product demo sections",
      "Pricing table integration",
      "CTA optimized layout",
      "Investor-ready presentation design",
    ],
  },
];

export const STATIC_STATS = [
  { value: "150+", label: "E-commerce Stores" },
  { value: "200+", label: "Custom Solutions" },
  { value: "1200+", label: "Happy Clients" },
  { value: "8+", label: "Years of Experience" },
];
