import type { TeamMember } from "@/types";

export const STATIC_TEAM: TeamMember[] = [
  {
    id: 1,
    name: "Sumaiya Rahman",
    role: "Head of Product",
    image: "/images/avatar1.png",
    initials: "SR",
    department: "Product",
    skills: ["Strategy", "Roadmap", "UX"],
    facebook: "#",
    linkedin: "#",
    is_active: true,
    sort_order: 1,
  },
  {
    id: 2,
    name: "Tanvir Ahmed",
    role: "Engineering Lead",
    image: "/images/avatar2.png",
    initials: "TA",
    department: "Engineering",
    skills: ["Backend", "Cloud", "APIs"],
    facebook: "#",
    linkedin: "#",
    is_active: true,
    sort_order: 2,
  },
  {
    id: 3,
    name: "Nusrat Jahan",
    role: "Design Lead",
    image: "/images/avatar3.png",
    initials: "NJ",
    department: "Design",
    skills: ["UI/UX", "Systems", "Brand"],
    facebook: "#",
    linkedin: "#",
    is_active: true,
    sort_order: 3,
  },
  {
    id: 4,
    name: "Rakib Hasan",
    role: "Frontend Developer",
    image: "/images/avatar1.png",
    initials: "RH",
    department: "Engineering",
    skills: ["React", "Next.js", "Tailwind"],
    facebook: "#",
    linkedin: "#",
    is_active: true,
    sort_order: 4,
  },
  {
    id: 5,
    name: "Ayesha Khan",
    role: "Product Designer",
    image: "/images/avatar2.png",
    initials: "AK",
    department: "Design",
    skills: ["Figma", "UX", "Research"],
    facebook: "#",
    linkedin: "#",
    is_active: true,
    sort_order: 5,
  },
];
