import { Testimonial } from "@/types";

export const STATIC_TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    name: "Tahmid Rahman",
    role: "Founder, Fashion DTC",
    quote: "They didn't just build our store — they built the engine our growth runs on. Order volume 3x in six months, and the site has never gone down.",
    metric: "3x order volume in 6 months",
    rating: 5,
    color: "#a78bfa",
    initials: "TR",
    is_active: true,
    sort_order: 1,
  },
  {
    id: 2,
    name: "Sadia Karim",
    role: "Head of Digital, Beauty Retail",
    quote: "We've worked with three agencies before Prochesta IT. Two missed deadlines. One delivered something we couldn't edit. Prochesta IT shipped on time and trained our team in two afternoons.",
    metric: "On-time launch, in-house ownership",
    rating: 5,
    color: "#ec4899",
    initials: "SK",
    is_active: true,
    sort_order: 2,
  },
  {
    id: 3,
    name: "Mehedi Hasan",
    role: "Co-founder, Electronics Marketplace",
    quote: "Lighthouse score 98. Mobile sales doubled in eight weeks. Our previous \"fast\" site scored 41. The numbers speak for themselves.",
    metric: "+118% mobile revenue in 8 weeks",
    rating: 5,
    color: "#34d399",
    initials: "MH",
    is_active: true,
    sort_order: 3,
  },
  {
    id: 4,
    name: "Nusrat Jahan",
    role: "Operations, Dhaka Grocery Brand",
    quote: "The fraud checker alone saved us about BDT 18 lakh in our first quarter. We thought it was a nice-to-have. It's the most important feature in the stack.",
    metric: "BDT 18L saved from blocked fraud",
    rating: 5,
    color: "#fbbf24",
    initials: "NJ",
    is_active: true,
    sort_order: 4,
  },
  {
    id: 5,
    name: "Rakib Ahmed",
    role: "CTO, B2B Distributor",
    quote: "Our retention support engineer responds inside 30 minutes — every time. After two years on Prochesta IT, we still feel like a priority client.",
    metric: "< 30-min support, 2 years running",
    rating: 5,
    color: "#12d7df",
    initials: "RA",
    is_active: true,
    sort_order: 5,
  },
  {
    id: 6,
    name: "Farhana Akter",
    role: "CEO, Lifestyle Brand",
    quote: "Their discovery workshop was the first time anyone asked us about our customers, not their tech stack. That's why the build worked.",
    metric: "Right-sized scope, no over-build",
    rating: 5,
    color: "#0ea5e9",
    initials: "FA",
    is_active: true,
    sort_order: 6,
  },
  {
    id: 7,
    name: "Imran Khan",
    role: "Engineering Lead, Mid-market Retailer",
    quote: "We migrated 24,000 SKUs and 3 years of orders with zero data loss and one hour of downtime. Best migration I've been part of.",
    metric: "0 data loss, 1-hour downtime, 24K SKUs",
    rating: 5,
    color: "#a855f7",
    initials: "IK",
    is_active: true,
    sort_order: 7,
  },
];
